#!/usr/bin/env python2
# encoding: utf-8

import sys
from src.anarchy import Anarchy

test = False
if '--test' in sys.argv:
    test = True

try:
    anarchy = Anarchy()
    anarchy.run_dialogs(test=test)
except KeyboardInterrupt:
    print "\nOh my God! They killed Kenny! ...You bastards!"
    exit(1)
